spring:
  application:
    name: store
  datasource:
    url: jdbc:mariadb://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Wan010102
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
  security:
    user:
      name: Willl
      password: Wan010102
